variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

image: maven:3.9.9-eclipse-temurin-11

stages:
  - build
  - test

cache:
  paths:
    - .m2/repository

before_script:
  - echo "Using Maven"
  - mvn -version

build:
  stage: build
  script:
    - mvn -B -DskipTests clean package -s settings.xml

test:
  stage: test
  script:
    - mvn -B test -s settings.xml